# We begin by loading the data
library(readr)
setwd("/home/jc/Documents")
HopeMbtiAP <- read_csv("HopeMbtiAP.csv")

# An exploratory data visualization through 
# correlation matrix plot
library(psych)
pairs.panels(FollowHappyB, 
             method = "spearman", 
             hist.col = "lightgreen",
             density = TRUE,  
             ellipses = TRUE,
             pch = 21,
             cex = 2.0,
             cex.axis = 2.5,
             cex.labels = 2.5,
             lwd = 2,
             rug = TRUE,
             stars = TRUE
)
library(semPlot)
semPaths(result, whatLabels = "std", layout = "tree", color = list(
  lat = rgb(255, 100, 118, maxColorValue = 255),
  man = rgb(155, 253, 175, maxColorValue = 255)),
  mar = c(10, 5, 10, 5), intercepts = FALSE, residuls = FALSE, nCharNodes = 0)

# This is the Confirmatory Factor Analysis for Spirituality
#



#
# This model specification was automatically generated by Onyx
#
#
# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- FollowHappy
model<-"
! regressions 
   Followership=~Followership__Interrel*Interrel
   Followership=~Followership__Gmemb*Gmemb
   Followership=~Followership__RelGroup*RelGroup
   Followership=~Followership__Cont2Gr*Cont2Gr
   Followership=~Followership__Toleran*Toleran
   Followership=~Followership__EmotInt*EmotInt
   Followership=~Followership__Support*Support
   Followership=~Followership__ConEnt*ConEnt
   Followership=~Followership__Learn*Learn
   Followership=~Followership__Flexibi*Flexibi
   Followership=~Followership__Comm*Comm
   Followership=~Followership__Achieve*Achieve
! residuals, variances and covariances
   Interrel ~~ VAR_Interrel*Interrel
   RelGroup ~~ VAR_RelGroup*RelGroup
   Toleran ~~ VAR_Toleran*Toleran
   ConEnt ~~ VAR_ConEnt*ConEnt
   Learn ~~ VAR_Learn*Learn
   Comm ~~ VAR_Comm*Comm
   Gmemb ~~ VAR_Gmemb*Gmemb
   Cont2Gr ~~ VAR_Cont2Gr*Cont2Gr
   EmotInt ~~ VAR_EmotInt*EmotInt
   Support ~~ VAR_Support*Support
   Flexibi ~~ VAR_Flexibi*Flexibi
   Achieve ~~ VAR_Achieve*Achieve
   Followership ~~ 1.0*Followership
! observed means
   Interrel~1;
   RelGroup~1;
   Toleran~1;
   ConEnt~1;
   Learn~1;
   Comm~1;
   Gmemb~1;
   Cont2Gr~1;
   EmotInt~1;
   Support~1;
   Flexibi~1;
   Achieve~1;
";
result1 <- lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
result1b <- lavaan(model, data=modelData, fixed.x=FALSE, missing="listwise", estimator = "DWLS");
summary(result1, fit.measures=TRUE);
summary(result1b, fit.measures=TRUE);

semTable(list("Model 1" = result1, "Model 2" = result1b),
         fits = c("chisq", "rmsea", "srmr", "cfi", "tli"),
         columns = c("estsestars", "rsquare" ,"p"),
         paramSets = c("loadings" , "slopes", "latentcovariances"),
         type = "latex", table.float = TRUE , longtable = FALSE,
         caption = "Statistical Estimated Parameters for the Spirituality Structural Model",
         label = "t1")
library(semPlot)
semPaths(result1, whatLabels = "std", layout = "tree", color = list(
  lat = rgb(255, 100, 118, maxColorValue = 255),
  man = rgb(155, 253, 175, maxColorValue = 255)),
  mar = c(10, 5, 10, 5), intercepts = FALSE, residuls = FALSE, nCharNodes = 0)

#
# This model specification was automatically generated by Onyx
#
#
# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- FollowHappy
model<-"
! regressions 
   Happiness=~Happiness__Happy*Happy
   Happiness=~Happiness__Compared*Compared
   Happiness=~Happiness__Embrace*Embrace
   Happiness=~Happiness__LittleHap*LittleHap
! residuals, variances and covariances
   Happy ~~ VAR_Happy*Happy
   Compared ~~ VAR_Compared*Compared
   Embrace ~~ VAR_Embrace*Embrace
   LittleHap ~~ VAR_LittleHap*LittleHap
   Happiness ~~ 1.0*Happiness
! observed means
   Happy~1;
   Compared~1;
   Embrace~1;
   LittleHap~1;
";
result1 <- lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
result1b <- lavaan(model, data=modelData, fixed.x=FALSE, missing="listwise", estimator = "DWLS");
summary(result1, fit.measures=TRUE);
summary(result1b, fit.measures=TRUE);

semTable(list("Model 1" = result1, "Model 2" = result1b),
         fits = c("chisq", "rmsea", "srmr", "cfi", "tli"),
         columns = c("estsestars", "rsquare" ,"p"),
         paramSets = c("loadings" , "slopes", "latentcovariances"),
         type = "latex", table.float = TRUE , longtable = FALSE,
         caption = "Statistical Estimated Parameters Hope Structural Model",
         label = "t2")
library(semPlot)
semPaths(result1, whatLabels = "std", layout = "tree", color = list(
  lat = rgb(255, 100, 118, maxColorValue = 255),
  man = rgb(155, 253, 175, maxColorValue = 255)),
  mar = c(10, 5, 10, 5), intercepts = FALSE, residuls = FALSE, nCharNodes = 0)


# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- FollowHappy
model<-"
! regressions 
   Followership=~Followership__Interrel*Interrel
   Followership=~Followership__Gmemb*Gmemb
   Followership=~Followership__RelGroup*RelGroup
   Followership=~Followership__Cont2Gr*Cont2Gr
   Followership=~Followership__Toleran*Toleran
   Followership=~Followership__Support*Support
   Followership=~Followership__ConEnt*ConEnt
   Followership=~Followership__Flexibi*Flexibi
   Followership=~Followership__Learn*Learn
   Followership=~Followership__Comm*Comm
   Followership=~Followership__Achieve*Achieve
   Followership=~Followership__EmotInt*EmotInt
   Happiness=~Happiness__Happy*Happy
   Happiness=~Happiness__Compared*Compared
   Happiness=~Happiness__Embrace*Embrace
   Happiness=~Happiness__LittleHap*LittleHap
   Happiness=~Happiness__Followership*Followership
! residuals, variances and covariances
   Interrel ~~ VAR_Interrel*Interrel
   RelGroup ~~ VAR_RelGroup*RelGroup
   Toleran ~~ VAR_Toleran*Toleran
   ConEnt ~~ VAR_ConEnt*ConEnt
   Learn ~~ VAR_Learn*Learn
   Comm ~~ VAR_Comm*Comm
   Gmemb ~~ VAR_Gmemb*Gmemb
   Cont2Gr ~~ VAR_Cont2Gr*Cont2Gr
   EmotInt ~~ VAR_EmotInt*EmotInt
   Support ~~ VAR_Support*Support
   Flexibi ~~ VAR_Flexibi*Flexibi
   Achieve ~~ VAR_Achieve*Achieve
   Happy ~~ VAR_Happy*Happy
   Compared ~~ VAR_Compared*Compared
   Embrace ~~ VAR_Embrace*Embrace
   LittleHap ~~ VAR_LittleHap*LittleHap
   Followership ~~ 1.0*Followership
   Happiness ~~ 1.0*Happiness
! observed means
   Interrel~1;
   RelGroup~1;
   Toleran~1;
   ConEnt~1;
   Learn~1;
   Comm~1;
   Gmemb~1;
   Cont2Gr~1;
   EmotInt~1;
   Support~1;
   Flexibi~1;
   Achieve~1;
   Happy~1;
   Compared~1;
   Embrace~1;
   LittleHap~1;
";
result1 <- lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
result1b <- lavaan(model, data=modelData, fixed.x=FALSE, missing="listwise", estimator = "DWLS");
summary(result1, fit.measures=TRUE);
summary(result1b, fit.measures=TRUE);

semTable(list("Model 1" = result1, "Model 2" = result1b),
         fits = c("chisq", "rmsea", "srmr", "cfi", "tli"),
         columns = c("estsestars", "rsquare" ,"p"),
         paramSets = c("loadings" , "slopes", "latentcovariances"),
         type = "latex", table.float = TRUE , longtable = FALSE,
         caption = "Statistical Estimated Parameters Hope Structural Model",
         label = "t3")
library(semPlot)
semPaths(result1, whatLabels = "std", layout = "tree", color = list(
  lat = rgb(255, 100, 118, maxColorValue = 255),
  man = rgb(155, 253, 175, maxColorValue = 255)),
  mar = c(10, 5, 10, 5), intercepts = FALSE, residuls = FALSE, nCharNodes = 0)

